
// This file has been generated by the GUI designer. Do not modify.
namespace Garvest
{
	public partial class LoginWindow
	{
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Label lblLogin;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Entry entry3;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Entry entry4;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Entry entry6;
		
		private global::Gtk.Alignment alignment1;
		
		private global::Gtk.Button button3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Garvest.LoginWindow
			this.HeightRequest = 200;
			this.Name = "Garvest.LoginWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			// Container child Garvest.LoginWindow.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 10;
			this.vbox3.BorderWidth = ((uint)(1));
			// Container child vbox3.Gtk.Box+BoxChild
			this.lblLogin = new global::Gtk.Label ();
			this.lblLogin.Name = "lblLogin";
			this.lblLogin.Ypad = 10;
			this.lblLogin.LabelProp = global::Mono.Unix.Catalog.GetString ("<b> Enter your Harvest Credentials </b>");
			this.lblLogin.UseMarkup = true;
			this.lblLogin.Justify = ((global::Gtk.Justification)(2));
			this.vbox3.Add (this.lblLogin);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lblLogin]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xpad = 10;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Domain");
			this.hbox1.Add (this.label6);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label6]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(22));
			// Container child hbox1.Gtk.Box+BoxChild
			this.entry3 = new global::Gtk.Entry ();
			this.entry3.WidthRequest = 169;
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '•';
			this.hbox1.Add (this.entry3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entry3]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString (".harvestapp.com");
			this.hbox1.Add (this.label7);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label7]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox3.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xpad = 10;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Email Address");
			this.hbox2.Add (this.label8);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label8]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.entry4 = new global::Gtk.Entry ();
			this.entry4.WidthRequest = 290;
			this.entry4.CanFocus = true;
			this.entry4.Name = "entry4";
			this.entry4.IsEditable = true;
			this.entry4.InvisibleChar = '•';
			this.hbox2.Add (this.entry4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entry4]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.Xpad = 10;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Password");
			this.hbox3.Add (this.label9);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label9]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.entry6 = new global::Gtk.Entry ();
			this.entry6.WidthRequest = 290;
			this.entry6.CanFocus = true;
			this.entry6.Name = "entry6";
			this.entry6.IsEditable = true;
			this.entry6.InvisibleChar = '•';
			this.hbox3.Add (this.entry6);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.entry6]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			w10.Padding = ((uint)(30));
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
			w11.Position = 3;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(50));
			this.alignment1.RightPadding = ((uint)(50));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.button3 = new global::Gtk.Button ();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.alignment1.Add (this.button3);
			this.vbox3.Add (this.alignment1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.alignment1]));
			w13.Position = 4;
			w13.Expand = false;
			w13.Fill = false;
			w13.Padding = ((uint)(1));
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 444;
			this.DefaultHeight = 214;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.button3.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
		}
	}
}
